[IMP] delivery_carrier_label_postlogistics: improve test coverage
grindtildeath/delivery-carrier pull request #2
Opened 2018-11-19 11:21 UTC by sebalix

2018-11-19 11:26 UTC, sebalix commented
ping @simahawk

2018-11-20 13:20 UTC, simahawk requested changes

2018-11-20 13:20 UTC, simahawk commented on delivery_carrier_label_postlogistics/tests/test_delivery.py
> +        self.carrier = self.env['delivery.carrier'].create({
do you need these records to be re-created for each test? If not use setUpClass pls (and the trick for tracking disable ;))

2018-11-20 13:20 UTC, simahawk commented on delivery_carrier_label_postlogistics/tests/test_delivery.py
> +        """Check allowed template options given that there is:
pls, respect https://www.python.org/dev/peps/pep-0257/#multi-line-docstrings
moreover they are printed on tests exec so you should really display only one small line ;)

2018-11-20 13:20 UTC, simahawk commented on delivery_carrier_label_postlogistics/tests/test_delivery.py
> +        single_option_types = SINGLE_OPTION_TYPES[:]
[x for x in SINGLE_OPTION_TYPES if x != 'resolution']

2018-11-20 13:30 UTC, sebalix commented on delivery_carrier_label_postlogistics/tests/test_delivery.py
> +        self.carrier = self.env['delivery.carrier'].create({
Yes I need them to be recreated as they are changed in some tests.

2018-11-20 13:32 UTC, simahawk commented on delivery_carrier_label_postlogistics/tests/test_delivery.py
> +        self.carrier = self.env['delivery.carrier'].create({
this is not a single transaction case so you should not get the same changes across tests

2018-11-20 13:47 UTC, sebalix commented on delivery_carrier_label_postlogistics/tests/test_delivery.py
> +        self.carrier = self.env['delivery.carrier'].create({
Okay! I'm not aware of the different test cases, 'll check that thanks.
By now, it's fixed.

2018-11-21 09:08 UTC, sebalix commented
Fixed

2018-11-21 09:13 UTC, simahawk approved these changes

2018-12-03 17:11 UTC, grindtildeath reviewed
Test looks good, but not complete. Would be great if you can add a logical test about :
1. create a sale order with the delivery method created in this test and a stockable product
2. confirm
3. Check that mandatory options are applied and not mandatory are available on the picking, and other options are not available.

Would you have time to do this ? Otherwise I'll merge and add a TODO :wink:

2018-12-04 08:17 UTC, sebalix commented
@grindtildeath no time ATM, maybe at the end of week but I really can't promise this, so go ahead if you want :)

2018-12-06 07:20 UTC, simahawk commented
@grindtildeath  go ahead... TODO comment is fine, we can get back later

2019-01-02 19:54 UTC, merged